### ISSUE TITLE
Access 로그 처리 방식 결정

### ISSUE THREAD

**Issue by jlee38266** [3sam5oh/webtoon-recommendation-service#16]
1. 어느 정보를 받아서 기록 할 건지.

**Comment by jhlee6515** [comment]
Access Log
- 사용자 정보(식별자, 성별, 나이)와 클릭 웹툰 정보(URL, 제목, 제공 플랫폼, 요일, 완결 여부, 무료 여부)
- json 포맷
- batch 사용해서 openSearch에 저장 (일단 하루 단위..?)
