### ISSUE TITLE
Backend 리소스 리서치

### ISSUE THREAD

**Issue by jlee38266** [3sam5oh/webtoon-recommendation-service#20]

**Comment by jhlee6515** [comment]
리소스
- JAVA(JDK)

- Spring Boot
- Lombok
- MapStruct

- Spring Security
- JWT

- Sops

- DB MySQL
- OpenSearch(with dependency)
- Loki
- Redis / ElasticCache
- Nginx

- LogStash / Fluentbit

- Doker
- K8s
- Grafana, Prometheus

- k6

- S3(with dependency)

- Open AI / Ollama
